SRCS = glob(['src/**'])
RESOURCES = glob(['resources/**'])

java_library(
  name = 'jgit',
  srcs = SRCS,
  resources = RESOURCES,
  deps = [
    '//lib:javaewah',
    '//lib:jsch',
    '//lib:httpcomponents',
    '//lib:servlet-api',
    '//lib:slf4j-api',
  ],
  visibility = [
		'//org.eclipse.jgit.lfs.server:jgit-lfs-server','PUBLIC'],
)

java_sources(
  name = 'jgit_src',
  srcs = SRCS + RESOURCES,
)
