
#Copyright (c) 2018 Contributors to the Eclipse Foundation
#
#  See the NOTICE file(s) distributed with this work for additional
#  information regarding copyright ownership.
#
#  This program and the accompanying materials are made available under the
#  terms of the Eclipse Public License 2.0 which is available at
#  http://www.eclipse.org/legal/epl-2.0
#
#  SPDX-License-Identifier: EPL-2.0
#

SRCS = glob(['src/**'])
RESOURCES = glob(['resources/**'])

java_library(
  name = 'jgit',
  srcs = SRCS,
  resources = RESOURCES,
  deps = [
    '//lib:javaewah',
    '//lib:jsch',
    '//lib:httpcomponents',
    '//lib:servlet-api',
    '//lib:slf4j-api',
  ],
  visibility = [
		'//org.eclipse.jgit.lfs.server:jgit-lfs-server','PUBLIC'],
)

java_sources(
  name = 'jgit_src',
  srcs = SRCS + RESOURCES,
)
