template: |
  # Remove sections you don't need.
  features:
    -
  issues:
    -
  upgrade:
    -
  deprecations:
    -
  critical:
    -
  security:
    -
  fixes:
    -
  other:
    -
encoding: utf8